//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int RES_CODIGO { get; set; }
        public System.DateTime RES_FECHA { get; set; }
        public System.DateTime RES_FECHA_INGRESO { get; set; }
        public System.DateTime RES_FECHA_SALIDA { get; set; }
        public string RES_ESTADO { get; set; }
        public int USU_CODIGO { get; set; }
        public int HAB_CODIGO { get; set; }
        public double RES_TOTAL { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
